import type { Coin, Trade, User, Holding } from "./types"

export const mockUser: User = {
  id: "1",
  username: "based.eth",
  avatar: "/pixel-art-avatar.png",
}

export const mockCoins: Coin[] = [
  {
    id: "1",
    type: "creator",
    symbol: "$JESSE",
    coinName: "Jesse Pollak",
    creatorName: "Jesse Pollak",
    creatorHandle: "@jessepollak",
    creatorAvatarUrl: "/jesse-pollak-crypto-founder-portrait.jpg",
    price: 0.0234,
    priceChange: 12.5,
    volume: 45200,
    liquidity: 125000,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    riskLabel: "NORMAL",
    creatorId: "creator-1",
  },
  {
    id: "2",
    type: "content",
    symbol: "$DEGEN",
    coinName: "Why I'm Bullish on Base",
    creatorName: "Degen Dave",
    creatorHandle: "@degendave",
    creatorAvatarUrl: "/degen-crypto-purple-avatar.jpg",
    contentImageUrl: "/bullish-chart-crypto-meme.jpg",
    price: 0.00089,
    priceChange: -8.3,
    volume: 12300,
    liquidity: 8500,
    launchedAt: new Date(Date.now() - 1000 * 60 * 23),
    riskLabel: "NEW",
    creatorId: "creator-2",
  },
  {
    id: "3",
    type: "content",
    symbol: "$SUMMER",
    coinName: "Base Summer Vibes",
    creatorName: "Sunny",
    creatorHandle: "@sunnyonchain",
    creatorAvatarUrl: "/sunny-beach-avatar.jpg",
    contentImageUrl: "/summer-beach-sunset.png",
    price: 0.0045,
    priceChange: 34.2,
    volume: 89000,
    liquidity: 4200,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    riskLabel: "LOW_LIQ",
    creatorId: "creator-3",
  },
  {
    id: "4",
    type: "creator",
    symbol: "$CART",
    coinName: "Coinbase Artist",
    creatorName: "The Coinbase Artist",
    creatorHandle: "@coinbaseart",
    creatorAvatarUrl: "/artist-paintbrush-creative-avatar.jpg",
    price: 0.0178,
    priceChange: 5.7,
    volume: 23400,
    liquidity: 67000,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    riskLabel: "NORMAL",
    creatorId: "creator-4",
  },
  {
    id: "5",
    type: "content",
    symbol: "$DREAM",
    coinName: "Onchain Dreams Cast",
    creatorName: "DreamWeaver",
    creatorHandle: "@dreamweaver",
    creatorAvatarUrl: "/dreamy-neon-avatar.jpg",
    contentImageUrl: "/neon-dream-cloud-abstract.jpg",
    price: 0.00234,
    priceChange: 156.8,
    volume: 234000,
    liquidity: 3100,
    launchedAt: new Date(Date.now() - 1000 * 60 * 45),
    riskLabel: "SPICY",
    creatorId: "creator-5",
  },
  {
    id: "6",
    type: "creator",
    symbol: "$ZORA",
    coinName: "Zora Legend",
    creatorName: "Zora OG",
    creatorHandle: "@zoraog",
    creatorAvatarUrl: "/zora-rainbow-creative-avatar.jpg",
    price: 0.0567,
    priceChange: -2.1,
    volume: 56700,
    liquidity: 189000,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
    riskLabel: "NORMAL",
    creatorId: "creator-6",
  },
]

export const mockTrades: Trade[] = [
  {
    id: "1",
    coinId: "1",
    side: "BUY",
    size: 0.05,
    price: 0.0234,
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
  },
  {
    id: "2",
    coinId: "1",
    side: "SELL",
    size: 0.02,
    price: 0.0231,
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: "3",
    coinId: "1",
    side: "BUY",
    size: 0.1,
    price: 0.0228,
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
  },
  {
    id: "4",
    coinId: "1",
    side: "BUY",
    size: 0.03,
    price: 0.0225,
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
  },
  {
    id: "5",
    coinId: "1",
    side: "SELL",
    size: 0.08,
    price: 0.0222,
    timestamp: new Date(Date.now() - 1000 * 60 * 18),
  },
]

export const mockHoldings: Holding[] = [
  {
    coin: mockCoins[0],
    amount: 1250,
    value: 29.25,
  },
  {
    coin: mockCoins[3],
    amount: 500,
    value: 8.9,
  },
  {
    coin: mockCoins[5],
    amount: 100,
    value: 5.67,
  },
]

export const mockUserCoin: Coin = {
  id: "user-coin",
  type: "creator",
  symbol: "$BASED",
  coinName: "Based User",
  creatorName: "based.eth",
  creatorHandle: "@basedeth",
  creatorAvatarUrl: "/pixel-art-based-avatar.jpg",
  price: 0.0089,
  priceChange: 23.4,
  volume: 12000,
  liquidity: 45000,
  launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
  riskLabel: "NORMAL",
}

export const mockUserContentCoins: Coin[] = [
  {
    id: "user-content-1",
    type: "content",
    symbol: "$GMBASED",
    coinName: "GM Based Fam",
    creatorName: "based.eth",
    creatorHandle: "@basedeth",
    creatorAvatarUrl: "/pixel-art-avatar.png",
    contentImageUrl: "/gm-sunrise-crypto-art.jpg",
    price: 0.0012,
    priceChange: 45.2,
    volume: 8900,
    liquidity: 3200,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    riskLabel: "NEW",
    creatorId: "1",
  },
  {
    id: "user-content-2",
    type: "content",
    symbol: "$BUILD",
    coinName: "Building in Public",
    creatorName: "based.eth",
    creatorHandle: "@basedeth",
    creatorAvatarUrl: "/pixel-art-avatar.png",
    contentImageUrl: "/code-developer-building.jpg",
    price: 0.0034,
    priceChange: 12.8,
    volume: 15600,
    liquidity: 8900,
    launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    riskLabel: "NORMAL",
    creatorId: "1",
  },
]

export interface Creator {
  id: string
  name: string
  handle: string
  avatarUrl: string
  bio: string
  creatorCoin: Coin
  contentCoins: Coin[]
}

export const mockCreators: Creator[] = [
  {
    id: "creator-1",
    name: "Jesse Pollak",
    handle: "@jessepollak",
    avatarUrl: "/jesse-pollak-crypto-founder-portrait.jpg",
    bio: "Building Base",
    creatorCoin: mockCoins[0],
    contentCoins: [],
  },
  {
    id: "creator-2",
    name: "Degen Dave",
    handle: "@degendave",
    avatarUrl: "/degen-crypto-purple-avatar.jpg",
    bio: "Full time degen, part time dev",
    creatorCoin: {
      id: "degen-creator",
      type: "creator",
      symbol: "$DAVE",
      coinName: "Degen Dave",
      creatorName: "Degen Dave",
      creatorHandle: "@degendave",
      creatorAvatarUrl: "/degen-crypto-purple-avatar.jpg",
      price: 0.0012,
      priceChange: 45.2,
      volume: 34000,
      liquidity: 12000,
      launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      riskLabel: "NORMAL",
      creatorId: "creator-2",
    },
    contentCoins: [mockCoins[1]],
  },
  {
    id: "creator-3",
    name: "Sunny",
    handle: "@sunnyonchain",
    avatarUrl: "/sunny-beach-avatar.jpg",
    bio: "Spreading good vibes onchain",
    creatorCoin: {
      id: "sunny-creator",
      type: "creator",
      symbol: "$SUNNY",
      coinName: "Sunny",
      creatorName: "Sunny",
      creatorHandle: "@sunnyonchain",
      creatorAvatarUrl: "/sunny-beach-avatar.jpg",
      price: 0.0078,
      priceChange: 8.9,
      volume: 18000,
      liquidity: 28000,
      launchedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
      riskLabel: "NORMAL",
      creatorId: "creator-3",
    },
    contentCoins: [mockCoins[2]],
  },
]
